services:
  postgres:
    image: postgres:{latest}
    environment:
      POSTGRES_DB: anki_clone_db
      POSTGRES_USER: edesousacosta
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
